# Battle Points Plugin 3.0.0
# @author     ucchy
# @license    LGPLv3
# @copyright  Copyright ucchy 2013

useVault: false
displayPointOnChat: true
displayPointOnChatWorlds: ['world']

useWebstat: true
webstatPortNumber: 8106

initialPoint: 1500
winBasePoint: 16
winOffsetPoint: 2
winBonusPointPercent: 4
winTeamBonusPoint: 10
ranks:
  novice:
    symbol: 'N'
    color: 'blue'
    border: 0
  bronze:
    symbol: 'B'
    color: 'aqua'
    border: 1700
  silver:
    symbol: 'S'
    color: 'gold'
    border: 1900
  gold:
    symbol: 'G'
    color: 'red'
    border: 2200
  platinum:
    symbol: 'P'
    color: 'light_purple'
    border: 2500
