name: BattlePoints
main: com.github.ucchyocean.bp.BattlePoints
version: 3.0.2
author: ucchy
description: Points system plugin for PVP
depend: []
softdepend: [ColorTeaming, Vault]
commands:
  battlepoints:
    description: Points system plugin for PVP
    aliases: bp
    usage: |
           /<command> rank [NumberOfView] - view point ranking.
           /<command> kdrank [NumberOfView] - view k/d rate ranking.
           /<command> krank [NumberOfView] - view kill count ranking.
           /<command> drank [NumberOfView] - view death count ranking.
           /<command> set (player) (point) - set player's point.
           /<command> team (number) - do teaming. (needs ColorTeaming plugin.)
           /<command> reload - reload configuration.
permissions:
  battlepoints.rank:
    description: Show point ranking command permission.
    default: true
  battlepoints.kdrank:
    description: Show K/D rate ranking command permission.
    default: true
  battlepoints.krank:
    description: Show kill count ranking command permission.
    default: true
  battlepoints.drank:
    description: Show death count ranking command permission.
    default: true
  battlepoints.set:
    description: Set player's point command permission.
    default: op
  battlepoints.team:
    description: Teaming command permission.
    default: op
  battlepoints.reload:
    description: Reload config command permission.
    default: op
  battlepoints.*:
    children:
      battlepoints.rank: true
      battlepoints.kdrank: true
      battlepoints.set: true
      battlepoints.team: true
      battlepoints.reload: true
    description: Allows all commands for BattlePoints.
