name: BattlePoints
main: com.github.ucchyocean.bp.BattlePoints
version: 2.2.2
author: ucchy
description: Points system plugin for PVP
depend: []
softdepend: [ColorTeaming, Vault]
commands:
  battlepoints:
    description: Points system plugin for PVP
    aliases: bp
    usage: |
           /<command> rank [NumberOfView] - ポイントランキングを参照します。
           /<command> kdrank [NumberOfView] - K/Dレートランキングを参照します。
           /<command> set (player) (point) - プレイヤーのポイントを設定します。
           /<command> team (number) - チームわけを実行します。ColorTeamingがロードされている必要があります。
           /<command> reload - config.ymlを再読み込みします。
permissions:
  battlepoints.rank:
    description: Show point ranking command permission.
    default: true
  battlepoints.kdrank:
    description: Show K/D rate ranking command permission.
    default: true
  battlepoints.set:
    description: Set player's point command permission.
    default: op
  battlepoints.team:
    description: Teaming command permission.
    default: op
  battlepoints.reload:
    description: Reload config command permission.
    default: op
  battlepoints.*:
    children:
      battlepoints.rank: true
      battlepoints.kdrank: true
      battlepoints.set: true
      battlepoints.team: true
      battlepoints.reload: true
    description: Allows all commands for BattlePoints.
